vich_uploader:
    db_driver: orm

    mappings:
        film_image:
            uri_prefix: /images/films
            upload_destination: '%kernel.project_dir%/public/images/films'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        festival_image:
            uri_prefix: /images/festivals
            upload_destination: '%kernel.project_dir%/public/images/festivals'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        edition_image:
            uri_prefix: /images/editions
            upload_destination: '%kernel.project_dir%/public/images/editions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
